env:
  global:
    - MAVEN_CMD="mvn --batch-mode --show-version"
    - secure: "A3DESTZ1fBaJnp2L4Dt10XLCahF1VJjICcNhnwKWdnwPHFGlx7ro51RIy5mWlqlplBpQCayzaTDbJnmXpE+cEbUTCKQwm0OYwDU1DAXz6+Mo/efSlq6nEpUw1hxW/0bTDz/GlI5tz437hx5NOJp2weY+sBGXnBL6vp0XybzkVeggJvK1Fz48T1fCXpeVuKCdaC9PoYpfRqP4JhqdCsCy9xUeZUWznep0J7/OCLHbVxondbiTRLDBNvPWUKIprq7HM3T8FNV37HODilXgw+fkTeAPBA6CrNrVWFC4PPCKjJc6txx8kyjevapI166QnqJ6xJgvMCvq/e45+lkvrrCCPopMpCqyHMU0PpvkVV70ewFOAYVf6qqWbQ2wf6CFUA9bCm7PLzipOipwYXWd3Bc+wtVGrvoV4ZxYf0A3ccQtivZ/WyHMtFaYIrpCrYxnLee7EKHLEIwvo9DU0a/vExJpWkjbsWRLisKJOUx01Eb1FcZ9PrfdBZiVG/mU8CAel+neZBxTdSgnfz+JWnx7/h4VB3tpIP5gjq9j+rRRSHddR3n7dQvQvT5QWW7MysifazakgPdz+eRfOmexwU06OhGo8Nc6WPwK1pQvxOElqYNKAcFDD98uokRXy+p9+LO4h0CrYofWen2A2Yyq+5OpJqoB5USCE1IzcwYksqi8EBVzvo4="
    - secure: "IDgPtaARfGKXEIfCIDxxhd0ICDbK5yX66Ik7dgPmzaL4Twi2La63fFYAQEhhAqFSrQY6sT13LrisDYvPCYsXda9qoXqsy61STE2j995Npu/4MAtJzsNr52ohTbXw6VI0acdBPtGV6eCp1DE7U25yeSEOfHmA1djjScloK612vdXVQOkD9TnlQAxXWz7g0+xM06Yg05tmA9NRV+yI1O5qjwT7R+h4dZP24OQn64yHFDBfvjIR4ytGgyJzMqxlpXXzqpQh0CzskFUJbhO2TkIL1VTrJO3SO9uoMLSlzwq0UzSXNbF+NefLGJ1r7rqfhFMAWfRTwSj9VhrIUOBcNpChIJsUw9G8iZ7z8CDRQYGTpHP46nsSTh4Wiien2Uv4x8F8qVlunAqewb0vo/mSH5tC7+KRJn5Sx1jozkMrYAU0UxtvwIBK63MSAV+aQGgcmA4kns8Bh/3GM8OHDHKY8x+9YChQ/hmszIAZD9/6DCnS6EZINl9zBkHxvkqFjTLv3aE9VkCaad0NqqrnvbZW3vFqtBE3hIfbHK2m8EmoW3S9WiGi4jK49UGRWLBzwKvRFCce3eAOd201jntjGcsQj1JJ+sgMVw3qPSidkt1ToV/QXLrz+zaHqGcA8QYDmyzYlXrTUT3VQPoWr6xOOQ+r50om61guScGF0QbR2JUUbwie6vg="
    - secure: "W/Ow6oCl5DWXuKVsD5Cs8UQXiEHxD86xTVbVdfZYcZW/zrl7uuAem2yA+Z1as7/NS2qCckgTVy0sq3BzBhMcN32P6/qvDxI2o0Y78UQHzJBBwX8PwEDjF3frgc3wwLTJSCebaiC7RvFPwUWvwcpi394g1xB/lbkTetk+KTKGpME22XcpVpdk52TSxn4BYUpbxGHFubkrhYF73v5K+rkfwtCvNFAXG7nRO8TspL5RRUiEkuu9zF892bkYMfLGktIrYrI69pXhxnqU5pnaj90sqNrmfrs9EBqdy6nhJ44yBN7iW46of4GrjrhgyU8GoHATmHVpmWLCHknr/olAqJzJW+hXIV43aJAS3kxJroDOg462iE9rn+slGbAVONMno8q2BZNjis45NU8jFEcwkfPECs7rULPP/a1FTkos2z35qaPEiY5Bg6tDpzRGRFlrEqc6aIjlWSaGA/bjH/uG/C2/WcW6aNooUR5PnGHqVv6fERT7UTADtlaPsWO4QVYKi2518eZAP8iPl+IJwj0TCw9dy1ekNctFWVq/o5CyNQAjxUt/5ICwyhzch/K+6Nvr7Xb+GJjwihX4dS/oRGSxD5PVqA3mhd1yzMA1FfcLfIJOfTS3e7bJZk8vIHumkA62QhJy87rCYBT3QzVvBKsxiLvtkyruxgP3E7XZNnqdn+TQcs8="

language: java

os:
  - linux

jdk:
  - openjdk11
  - openjdk15

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - openssl aes-256-cbc -K $encrypted_53b03684417e_key -iv $encrypted_53b03684417e_iv -in gpg-key-FB208B6E.asc.enc -out gpg-key-FB208B6E.asc -d
  - gpg --batch --fast-import gpg-key-FB208B6E.asc
  - if [ -n "$TRAVIS_TAG" ]; then $MAVEN_CMD versions:set -DnewVersion=$TRAVIS_TAG; fi

install:
  - $MAVEN_CMD dependency:go-offline

script:
  - $MAVEN_CMD test
  - if [[ "$TRAVIS_JDK_VERSION" == "openjdk15" ]]; then
      $MAVEN_CMD clean deploy --activate-profiles deploy --settings settings.xml -DskipTests -Dgpg.passphrase=$GPG_PASSPHRASE;
    fi

after_success:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_JDK_VERSION" == "openjdk15" ]]; then
      $MAVEN_CMD nexus-staging:release --activate-profiles deploy --settings settings.xml;
    fi

after_failure:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_JDK_VERSION" == "openjdk15" ]]; then
      $MAVEN_CMD nexus-staging:drop --activate-profiles deploy --settings settings.xml;
    fi

deploy:
  provider: releases
  token:
    secure: "Ib0JQfuIsQ3RE2PYPeogmvTbyOvC6RJ5Y4m2SZVd8z35paB+lEUTT0ZiMIkbFsM56Xt93HA04IVb8BgkT44D1PothfmOPyYLQ6I8SpPzlqsrssPIrMmC7KtIM+vv6Sn6fKh9rF3CbvSkJFpsEpRObL+i3PfNdlzdxtqFafD8Lgi6BeKolKM/+9r99y/6U77bKZOXXEjB0gThxXaoYjQ0TXBRjIX7pSISXiZUCDubSH+V5panBJYdto1cgOFBEySvvuNfYtw+sibntUwuWlEonRv/GHL48HOiYYsX6ya+EpOSs25qkCvq5IpHN2Io1o+BlTrC3UAYLSr8KoeGGj2a4xxjlNdMGpV36ySl/x6Zs3gWixnMiqcVoDevpUpecDSPe7/Al0Z+JmgtjHMjCMT/yHkJy9dzsvMTfb7NlXNYQa9MmjCMWYzXbSoJsjuVriQJ4ujcNgppMxA5Ora8RKDH6lJiCVbMtQGkfT7h3mHQ6aiO9l/hFoEZkN0AVxwIsIntLKAitivQnIdpdC340Av5gk/EoUrPyvnkqo5g3Uh3WWcqCKBJ8h1HXMDm7UyRPRFrTFNng1/drzL3RrzaBQ03cbGn7wNsUmIhq/0Wb6kFVcoX7LR4ljI0Rcx743Z+d07aMWyAfGrvWpGvCzi/4ZL2srUw8usWZyPDRJBbh1wGSVo="
  skip_cleanup: true
  file_glob: true
  file:
    - target/rhpam-dependencies-*.pom
    - target/rhpam-dependencies-*.pom.asc
  on:
    repo: juliaaano/rhpam-dependencies
    branch: master
    tags: true
    jdk: openjdk15
